[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "running-nmor-opm"
version = "0.1.0"
description = "Scripts/software for characterizing, running, and testing NMOR OPM gradiometer"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "running-nmor-opm contributors" }]

[tool.ruff]
extend = "ruff.toml"
